name: ecommerceapp
description: "App Flutter para e-commerce con autenticación y roles de usuario"
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1  # Para llamadas HTTP a la API
  shared_preferences: ^2.2.3  # Para almacenamiento persistente del token
  provider: ^6.1.2  # Opcional: Para gestión de estado (usuario, carrito)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true